//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessRuleEngine.Validations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessRuleEngine.Validations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent cannot be empty..
        /// </summary>
        internal static string AgentCannotBeEmpty {
            get {
                return ResourceManager.GetString("AgentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer cannot be empty..
        /// </summary>
        internal static string CustomerCannotBeEmpty {
            get {
                return ResourceManager.GetString("CustomerCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer email cannot be empty..
        /// </summary>
        internal static string CustomerEmailCannotBeEmpty {
            get {
                return ResourceManager.GetString("CustomerEmailCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department cannot be empty..
        /// </summary>
        internal static string DepartmentCannotBeEmpty {
            get {
                return ResourceManager.GetString("DepartmentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a duplicate slip since department is not provided..
        /// </summary>
        internal static string DepartmentNotProvided {
            get {
                return ResourceManager.GetString("DepartmentNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a duplicate slip since this is not intended for royality department..
        /// </summary>
        internal static string DepartmentNotRoyality {
            get {
                return ResourceManager.GetString("DepartmentNotRoyality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership cannot be empty..
        /// </summary>
        internal static string MembershipCannotBeEmpty {
            get {
                return ResourceManager.GetString("MembershipCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment object is empty..
        /// </summary>
        internal static string PaymentCannotBeEmpty {
            get {
                return ResourceManager.GetString("PaymentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment value cannot be 0..
        /// </summary>
        internal static string PaymentValueCannotBeZeo {
            get {
                return ResourceManager.GetString("PaymentValueCannotBeZeo", resourceCulture);
            }
        }
    }
}
